# Generated by Django 3.2 on 2021-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='description',
        ),
        migrations.AddField(
            model_name='record',
            name='arrangement_type',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='expertise_status',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='payment_status',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='record_number',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='sentence_status',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='updated_state',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(default='python', max_length=50),
        ),
    ]
