# Generated by Django 3.2 on 2021-04-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20210414_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sentence_status',
        ),
    ]
