# Generated by Django 3.2 on 2021-04-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_remove_record_sentence_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='updated_state',
            new_name='action_lawyer',
        ),
        migrations.AddField(
            model_name='record',
            name='comments',
            field=models.CharField(default='python', max_length=50),
        ),
    ]
