# Generated by Django 3.2 on 2021-04-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20210421_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='comments',
            field=models.CharField(default='python', max_length=550),
        ),
    ]
