# Generated by Django 3.2 on 2021-04-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_record_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='city',
            field=models.CharField(default='python', max_length=50),
        ),
        migrations.AddField(
            model_name='record',
            name='dependency',
            field=models.CharField(default='python', max_length=50),
        ),
    ]
